// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhtfrwhyjglfpcsmmcfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJodGZyd2h5amdsZnBjc21tY2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4ODE5MTUsImV4cCI6MjA1NzQ1NzkxNX0.PqcG8lrIBSaIVF_INIf-3EeUgzlBbOxEO0vVXdzxkNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);